# Build lcov coverage and deploy it to GitHub Pages
name: Deploy coverage report to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install coverage tools
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Configure CMake (coverage)
        run: >
          cmake -B ${{ github.workspace }}/build-coverage
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_FLAGS="-DNDEBUG -DPCP_MAX_LOG_LEVEL=5 -O0 -g"
          -DENABLE_GCOV=ON
          -S ${{ github.workspace }}

      - name: Build (coverage)
        run: cmake --build ${{ github.workspace }}/build-coverage

      - name: Test (coverage)
        run: ctest --test-dir ${{ github.workspace }}/build-coverage --output-on-failure

      - name: Generate coverage report
        run: |
          cd ${{ github.workspace }}/build-coverage
          rm -f cli-client/CMakeFiles/pcpnatpmpc.dir/*.gcda
          lcov -c --directory . --output-file info
          lcov --ignore-errors unused --remove info '/usr/*' '*/tests/*' '*/test-server/*' '*/cli-client/*' '*/CMakeFiles/*' --output-file info.filtered
          genhtml -o coverage-report info.filtered

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/build-coverage/coverage-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5